In [1]:
!nvidia-smi

Fri Jan  5 16:08:46 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-PCIE-16GB           Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P0              27W / 250W |      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np

print(torch.__version__)

2.0.0


## Introduction to Tensors


In [3]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector= torch.tensor([2,3])
vector.ndim

1

In [7]:
matrix  = torch.tensor([[1,2],
                        [6,7]])
matrix

tensor([[1, 2],
        [6, 7]])

In [8]:
matrix.shape

torch.Size([2, 2])

In [9]:
tensor = torch.tensor([[[1,2,3],
                      [2,4,8],
                      [5,9,1]],    
                      [[1,2,3],
                      [2,4,8],
                      [5,9,1]]])
tensor


tensor([[[1, 2, 3],
         [2, 4, 8],
         [5, 9, 1]],

        [[1, 2, 3],
         [2, 4, 8],
         [5, 9, 1]]])

In [10]:
tensor[1][0][0]

tensor(1)

### Random tensors


In [11]:
#create a random tensor size (3,4,4)

random_tensor = torch.rand(3, 4, 4)
random_tensor

tensor([[[0.7683, 0.1189, 0.2620, 0.0672],
         [0.2142, 0.0516, 0.2898, 0.2483],
         [0.3647, 0.6772, 0.7018, 0.5435],
         [0.6433, 0.3496, 0.2669, 0.9381]],

        [[0.7761, 0.0813, 0.1666, 0.7682],
         [0.1159, 0.9098, 0.5858, 0.9228],
         [0.2474, 0.8572, 0.2274, 0.3085],
         [0.0115, 0.4311, 0.0803, 0.4034]],

        [[0.0726, 0.1086, 0.3197, 0.7618],
         [0.1941, 0.0264, 0.0448, 0.3276],
         [0.0698, 0.6088, 0.5755, 0.1724],
         [0.1496, 0.1002, 0.4617, 0.0485]]])

In [12]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channels
random_image_size_tensor

tensor([[[0.6259, 0.0998, 0.6982],
         [0.9254, 0.7321, 0.7644],
         [0.0600, 0.0970, 0.9117],
         ...,
         [0.5446, 0.3965, 0.7256],
         [0.1416, 0.1524, 0.7457],
         [0.9405, 0.3553, 0.8685]],

        [[0.7322, 0.9208, 0.2977],
         [0.7929, 0.4824, 0.5517],
         [0.2502, 0.1082, 0.9405],
         ...,
         [0.6106, 0.7610, 0.7167],
         [0.2931, 0.9812, 0.4582],
         [0.9946, 0.0206, 0.2195]],

        [[0.7163, 0.9894, 0.9620],
         [0.5935, 0.4251, 0.0289],
         [0.9937, 0.4802, 0.7556],
         ...,
         [0.9864, 0.5377, 0.7901],
         [0.4889, 0.8635, 0.3182],
         [0.5853, 0.7462, 0.8281]],

        ...,

        [[0.4147, 0.1508, 0.0793],
         [0.1153, 0.3566, 0.6763],
         [0.9865, 0.9566, 0.8306],
         ...,
         [0.0559, 0.6181, 0.0269],
         [0.8364, 0.9615, 0.5436],
         [0.1552, 0.9150, 0.9955]],

        [[0.9269, 0.6724, 0.2014],
         [0.7196, 0.2589, 0.6458],
         [0.

### Zeros  and ones 

In [13]:
#create a tensor of all zeros

zeros = torch.zeros(size=(224, 224, 3))
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [14]:
random_image_size_tensor*zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [15]:
one_to_ten=torch.arange(1,11,1)

In [16]:
tensor_zeros = torch.zeros_like(input=one_to_ten)
tensor_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Manipulating Tensors (tensor operations)

Tensor operations include:

    * Addition
    * Subtraction
    * Multiplication
    * Division
    * Matrix Mul

In [17]:
#Create a tensor

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [18]:
# Multiply tensor by 10

tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [19]:
# Divide the tensor by 10
tensor = tensor / 10
tensor

tensor([1., 2., 3.])

In [20]:
# Matrix Multiplication

# Element wise multiplication
tensor1 = torch.rand(size=(3,2))
tensor2 = torch.rand(size=(2,3))

tensor1
tensor2

out = torch.matmul(tensor1,tensor2)
out



tensor([[0.1923, 1.2084, 0.0604],
        [0.1998, 1.2570, 0.0631],
        [0.1831, 1.3051, 0.0927]])